name: xeus-robot
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - xeus-python>=0.10.2,<0.11
  - robotframework-interpreter
  - robotframework-lsp
  - xtl
  - cppzmq
  - nlohmann_json
  - pybind11
  - pybind11_json
  - pip
  - robotframework-interpreter>=0.6.2,<0.7
  # Test dependencies
  - jupyter_kernel_test
