name: xeus-robot
channels:
  - conda-forge
dependencies:
  - xeus-robot
  - robotframework-lsp
  - robotframework-seleniumlibrary
  - robotframework-jupyterlibrary
  - ipywidgets>=7.6
  - jupyterlab=3
